name:                free-accelerate
version:             0.1.0
github:              "fizruk/free-accelerate"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2022 Nickolay Kudasov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/free-accelerate#readme>

dependencies:
- accelerate
- accelerate-llvm
- accelerate-llvm-native
- base >= 4.7 && < 5
- deriving-compat
- free
- mtl

library:
  source-dirs: src
